### ISSUE TITLE
404 when getting media_nodes

### ISSUE THREAD

**Issue by devboy** [sborod/ruby-instagram-scraper#5]
Looks like something changed on instagrams side...

```
/Users/devboy/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 404 Not Found (OpenURI::HTTPError)
from /Users/devboy/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
from /Users/devboy/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
from /Users/devboy/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
from /Users/devboy/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
from /Users/devboy/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
from /Users/devboy/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:717:in `open'
from /Users/devboy/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:35:in `open'
from /Users/devboy/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby-instagram-scraper-0.1.7/lib/ruby-instagram-scraper.rb:20:in `get_user_media_nodes'
from lib/instagram.rb:27:in `block (2 levels) in <main>'
from lib/instagram.rb:25:in `each'
from lib/instagram.rb:25:in `block in <main>'
from lib/instagram.rb:22:in `loop'
from lib/instagram.rb:22:in `<main>'

```

**Comment by devboy** [comment]
My bad. Was trying to get images for a deleted account.
